release: false
server_name: "grchallengeapi"
server_host: "http://localhost"
server_port: "8011"
database_config:
  database_driver: "postgres"
  database_url: "localhost"
  database_port: "5433"
  database_name: "grdb"
  database_username: "postgres"
  database_password: "asdfghjkl"
  database_log_enabled: true
  database_disable_ssl_mode: true
git_scanner_config:
  root_path: "temp"
git_scanner_mq_config:
  kafka_broker_url: 206.189.89.184:29092
  kafka_server_id: git_repository_scanner_01
