release: false
server_name: "grchallengeapi"
server_host: "http://localhost"
server_port: "8011"
database_config:
  database_driver: "postgres"
  database_url: "localhost"
  database_port: "5433"
  database_name: "grdb"
  database_username: "postgres"
  database_password: "asdfghjkl"
  database_log_enabled: true
  database_disable_ssl_mode: true
git_config:
  root_path: "temp"
